terraform {
  required_version = ">= 1.5.0"
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "~> 5.0"
    }
  }
}

provider "google" {
  project = var.project_id
  region  = var.region
}

data "google_project" "project" {
  project_id = var.project_id
}

# ─────────────────────────────────────────────
# 1. Enable Required APIs
# ─────────────────────────────────────────────
resource "google_project_service" "apis" {
  for_each = toset([
    "iam.googleapis.com",
    "iamcredentials.googleapis.com",
    "storage.googleapis.com",
    "firestore.googleapis.com",
    "pubsub.googleapis.com",
    "cloudfunctions.googleapis.com",
    "run.googleapis.com",
    "eventarc.googleapis.com",
    "bigquery.googleapis.com",
    "artifactregistry.googleapis.com",
  ])
  service            = each.key
  disable_on_destroy = false
}

# ─────────────────────────────────────────────
# 2. GCS Buckets
# ─────────────────────────────────────────────
resource "google_storage_bucket" "pdf_manifests" {
  name                        = "${var.project_id}-pdf-manifests"
  location                    = var.region
  force_destroy               = true
  uniform_bucket_level_access = true

  lifecycle_rule {
    condition { age = 90 }
    action { type = "Delete" }
  }

  cors {
    origin          = ["*"]
    method          = ["GET", "POST", "PUT"]
    response_header = ["Content-Type"]
    max_age_seconds = 3600
  }

  depends_on = [google_project_service.apis]
}

# Voice Notes — temporary MP3 files generated by Service E (ElevenLabs TTS).
# Objects are publicly readable so Twilio can fetch them without signed URLs.
# Lifecycle rule deletes objects after 1 day — they are transient alert audio.
#
# Note: if the GCP org policy constraints/iam.allowedPolicyMemberDomains blocks
# allUsers bindings, remove the google_storage_bucket_iam_member below and
# switch Service E to generate signed URLs instead of public GCS URLs.
resource "google_storage_bucket" "voice_notes" {
  name                        = "${var.project_id}-voice-notes"
  location                    = var.region
  force_destroy               = true
  uniform_bucket_level_access = true

  lifecycle_rule {
    condition { age = 1 }
    action { type = "Delete" }
  }

  depends_on = [google_project_service.apis]
}

resource "google_storage_bucket_iam_member" "voice_notes_public_read" {
  bucket = google_storage_bucket.voice_notes.name
  role   = "roles/storage.objectViewer"
  member = "allUsers"
}

# ─────────────────────────────────────────────
# 3. Artifact Registry — Docker repository
# ─────────────────────────────────────────────
resource "google_artifact_registry_repository" "agenticterps" {
  repository_id = "agenticterps"
  format        = "DOCKER"
  location      = var.region
  description   = "AgenticTerps Docker images"

  depends_on = [google_project_service.apis]
}

# ─────────────────────────────────────────────
# Service Account — Service A seed script
# ─────────────────────────────────────────────
resource "google_service_account" "service_a_seed" {
  account_id   = "service-a-seed"
  display_name = "Service A — Bootstrap Seed Script"
  description  = "Used by seed.py to write shipment documents to Firestore."
  project      = var.project_id

  depends_on = [google_project_service.apis]
}

resource "google_project_iam_member" "service_a_firestore" {
  project = var.project_id
  role    = "roles/datastore.user"
  member  = "serviceAccount:${google_service_account.service_a_seed.email}"

  depends_on = [google_service_account.service_a_seed]
}

# ─────────────────────────────────────────────
# Service Account — Service B (Telemetry Ingestion API)
# Cloud Function — receives UI simulator telemetry, writes live state
# to Firestore, and publishes to the telemetry-stream Pub/Sub topic.
# No Cloud Run invoker or Artifact Registry access needed (Cloud Function,
# not Cloud Run).
# ─────────────────────────────────────────────
resource "google_service_account" "service_b" {
  account_id   = "service-b-telemetry"
  display_name = "Service B — Telemetry Ingestion API"
  description  = "Used by the telemetry Cloud Function to write live telemetry state to Firestore and publish to telemetry-stream."
  project      = var.project_id

  depends_on = [google_project_service.apis]
}

# Read/write shipment documents in Firestore
# Required for: shipment existence check + live_telemetry map write
resource "google_project_iam_member" "service_b_firestore" {
  project = var.project_id
  role    = "roles/datastore.user"
  member  = "serviceAccount:${google_service_account.service_b.email}"

  depends_on = [google_service_account.service_b]
}

# Publish telemetry readings to the telemetry-stream topic
# Service C subscribes to this topic to run anomaly detection
resource "google_pubsub_topic_iam_member" "service_b_telemetry_publisher" {
  project = var.project_id
  topic   = google_pubsub_topic.telemetry_stream.name
  role    = "roles/pubsub.publisher"
  member  = "serviceAccount:${google_service_account.service_b.email}"

  depends_on = [google_service_account.service_b, google_pubsub_topic.telemetry_stream]
}

# ─────────────────────────────────────────────
# Service Account — Service C (Monitoring & Anomaly Agent)
# ─────────────────────────────────────────────
resource "google_service_account" "service_c" {
  account_id   = "service-c-monitoring"
  display_name = "Service C — Monitoring & Anomaly Agent"
  project      = var.project_id
  depends_on   = [google_project_service.apis]
}

# Read shipment documents from Firestore
resource "google_project_iam_member" "service_c_firestore" {
  project = var.project_id
  role    = "roles/datastore.user"
  member  = "serviceAccount:${google_service_account.service_c.email}"
}

# Publish messages to risk-detected topic
resource "google_pubsub_topic_iam_member" "service_c_risk_publisher" {
  project = var.project_id
  topic   = google_pubsub_topic.risk_detected.name
  role    = "roles/pubsub.publisher"
  member  = "serviceAccount:${google_service_account.service_c.email}"
}

# Allow Cloud Run to be invoked (for Pub/Sub push auth)
resource "google_project_iam_member" "service_c_pubsub_invoker" {
  project = var.project_id
  role    = "roles/run.invoker"
  member  = "serviceAccount:${google_service_account.service_c.email}"
}

# Allow Service C SA to pull images from Artifact Registry
resource "google_artifact_registry_repository_iam_member" "service_c_ar_reader" {
  repository = google_artifact_registry_repository.agenticterps.name
  location   = var.region
  role       = "roles/artifactregistry.reader"
  member     = "serviceAccount:${google_service_account.service_c.email}"
}

# ─────────────────────────────────────────────
# Service Account — Service D (Orchestrator Agent)
# Cloud Run — subscribes to risk-detected Pub/Sub topic,
# runs LangChain + Claude agent, writes to Firestore pending-approvals
# and approved-actions collections.
# ─────────────────────────────────────────────
resource "google_service_account" "service_d" {
  account_id   = "service-d-orchestrator"
  display_name = "Service D — Orchestrator Agent"
  description  = "Runs the LangChain orchestrator agent. Reads shipments from Firestore, writes pending-approvals and approved-actions."
  project      = var.project_id
  depends_on   = [google_project_service.apis]
}

# Read shipment metadata + write pending-approvals + approved-actions
resource "google_project_iam_member" "service_d_firestore" {
  project    = var.project_id
  role       = "roles/datastore.user"
  member     = "serviceAccount:${google_service_account.service_d.email}"
  depends_on = [google_service_account.service_d]
}

# Allow Pub/Sub to invoke this Cloud Run service (push subscription auth)
resource "google_project_iam_member" "service_d_pubsub_invoker" {
  project    = var.project_id
  role       = "roles/run.invoker"
  member     = "serviceAccount:${google_service_account.service_d.email}"
  depends_on = [google_service_account.service_d]
}

# Pull Docker image from Artifact Registry
resource "google_artifact_registry_repository_iam_member" "service_d_ar_reader" {
  repository = google_artifact_registry_repository.agenticterps.name
  location   = var.region
  role       = "roles/artifactregistry.reader"
  member     = "serviceAccount:${google_service_account.service_d.email}"
  depends_on = [google_service_account.service_d]
}

# ─────────────────────────────────────────────
# Service Account — Service E (Execution Agent)
# Cloud Run — receives approved risk events from execute-actions Pub/Sub topic,
# sends email/SMS/voice notifications, and writes to BigQuery audit log.
# ─────────────────────────────────────────────
resource "google_service_account" "service_e" {
  account_id   = "service-e-execution"
  display_name = "Service E — Execution Agent"
  description  = "Sends email/SMS/voice notifications and writes BigQuery audit logs after human approval."
  project      = var.project_id
  depends_on   = [google_project_service.apis]
}

# Read/write pending_approvals documents in Firestore (update status after execution)
resource "google_project_iam_member" "service_e_firestore" {
  project = var.project_id
  role    = "roles/datastore.user"
  member  = "serviceAccount:${google_service_account.service_e.email}"

  depends_on = [google_service_account.service_e]
}

# Write execution records to BigQuery compliance_trail.audit_log
resource "google_project_iam_member" "service_e_bigquery" {
  project = var.project_id
  role    = "roles/bigquery.dataEditor"
  member  = "serviceAccount:${google_service_account.service_e.email}"

  depends_on = [google_service_account.service_e]
}

# Allow Cloud Run to be invoked (for Pub/Sub push authentication)
resource "google_project_iam_member" "service_e_pubsub_invoker" {
  project = var.project_id
  role    = "roles/run.invoker"
  member  = "serviceAccount:${google_service_account.service_e.email}"

  depends_on = [google_service_account.service_e]
}

# Pull Docker image from Artifact Registry
resource "google_artifact_registry_repository_iam_member" "service_e_ar_reader" {
  repository = google_artifact_registry_repository.agenticterps.name
  location   = var.region
  role       = "roles/artifactregistry.reader"
  member     = "serviceAccount:${google_service_account.service_e.email}"

  depends_on = [google_service_account.service_e]
}

# Upload and manage voice note MP3s in the voice-notes GCS bucket
resource "google_storage_bucket_iam_member" "service_e_voice_notes_writer" {
  bucket = google_storage_bucket.voice_notes.name
  role   = "roles/storage.objectAdmin"
  member = "serviceAccount:${google_service_account.service_e.email}"

  depends_on = [google_service_account.service_e, google_storage_bucket.voice_notes]
}

# ─────────────────────────────────────────────
# 4. Firestore Database (Native mode)
# ─────────────────────────────────────────────
#
# deletion_policy = "DELETE" ensures terraform destroy actually deletes
# the database in GCP rather than just removing it from state (ABANDON).
# Note: GCP soft-deletes Firestore databases for 24 hours after deletion,
# so re-creating with the same name requires waiting 24 hours or using
# a different name.
# ─────────────────────────────────────────────
resource "google_firestore_database" "main" {
  project                 = var.project_id
  name                    = "cargo-monitor"
  location_id             = var.firestore_location
  type                    = "FIRESTORE_NATIVE"
  deletion_policy         = "DELETE"
  delete_protection_state = "DELETE_PROTECTION_DISABLED"

  depends_on = [google_project_service.apis]
}

# ─────────────────────────────────────────────
# 5. Pub/Sub Topics
# ─────────────────────────────────────────────

# Service B → Service C: live sensor data
resource "google_pubsub_topic" "telemetry_stream" {
  name       = "telemetry-stream"
  depends_on = [google_project_service.apis]
}

# Service C → Service D: anomaly / risk detected
resource "google_pubsub_topic" "risk_detected" {
  name       = "risk-detected"
  depends_on = [google_project_service.apis]
}

# Service D → Service E: human approved the plan
resource "google_pubsub_topic" "execute_actions" {
  name       = "execute-actions"
  depends_on = [google_project_service.apis]
}

# Dead-letter topic (optional but recommended for production)
resource "google_pubsub_topic" "dead_letter" {
  name       = "dead-letter"
  depends_on = [google_project_service.apis]
}

# ─────────────────────────────────────────────
# 6. Pub/Sub Subscriptions
# Update push_endpoint values after each Cloud Run deploy
# ─────────────────────────────────────────────

resource "google_pubsub_subscription" "telemetry_stream_sub" {
  name  = "telemetry-stream-sub"
  topic = google_pubsub_topic.telemetry_stream.name

  ack_deadline_seconds       = 60
  message_retention_duration = "600s"

  push_config {
    push_endpoint = var.service_c_url != "" ? "${var.service_c_url}/pubsub/telemetry" : "https://placeholder.invalid/pubsub/telemetry"
    attributes    = { x-goog-version = "v1" }
  }

  retry_policy {
    minimum_backoff = "10s"
    maximum_backoff = "300s"
  }

  dead_letter_policy {
    dead_letter_topic     = google_pubsub_topic.dead_letter.id
    max_delivery_attempts = 5
  }
}

resource "google_pubsub_subscription" "risk_detected_sub" {
  name  = "risk-detected-sub"
  topic = google_pubsub_topic.risk_detected.name

  ack_deadline_seconds       = 120
  message_retention_duration = "600s"

  push_config {
    push_endpoint = var.service_d_url != "" ? "${var.service_d_url}/risk-detected" : "https://placeholder.invalid/risk-detected"
    oidc_token {
      service_account_email = google_service_account.service_d.email
    }
    attributes = { x-goog-version = "v1" }
  }

  retry_policy {
    minimum_backoff = "15s"
    maximum_backoff = "600s"
  }

  dead_letter_policy {
    dead_letter_topic     = google_pubsub_topic.dead_letter.id
    max_delivery_attempts = 5
  }
}

resource "google_pubsub_subscription" "execute_actions_sub" {
  name  = "execute-actions-sub"
  topic = google_pubsub_topic.execute_actions.name

  ack_deadline_seconds       = 120
  message_retention_duration = "600s"

  push_config {
    push_endpoint = var.service_e_url != "" ? "${var.service_e_url}/pubsub/execute" : "https://placeholder.invalid/pubsub/execute"
    attributes    = { x-goog-version = "v1" }
  }

  retry_policy {
    minimum_backoff = "10s"
    maximum_backoff = "300s"
  }

  dead_letter_policy {
    dead_letter_topic     = google_pubsub_topic.dead_letter.id
    max_delivery_attempts = 5
  }
}

# ─────────────────────────────────────────────
# 7. BigQuery Dataset – Compliance Trail
# ─────────────────────────────────────────────
resource "google_bigquery_dataset" "compliance_trail" {
  dataset_id                 = "compliance_trail"
  location                   = var.region
  delete_contents_on_destroy = true

  depends_on = [google_project_service.apis]
}

resource "google_bigquery_table" "audit_log" {
  dataset_id          = google_bigquery_dataset.compliance_trail.dataset_id
  table_id            = "audit_log"
  deletion_protection = false

  schema = jsonencode([
    { name = "shipment_id", type = "STRING", mode = "REQUIRED" },
    { name = "event_type", type = "STRING", mode = "REQUIRED" },
    { name = "actor", type = "STRING", mode = "NULLABLE" },
    { name = "details", type = "JSON", mode = "NULLABLE" },
    { name = "timestamp", type = "TIMESTAMP", mode = "REQUIRED" },
  ])
}

# Frontend Node/Express app identity
# Use this service account when deploying the frontend so it can:
# - read and update Firestore documents used by the dashboard/approval flow
# - publish approved actions to the execute-actions Pub/Sub topic
resource "google_service_account" "frontend" {
  account_id   = "frontend-ui"
  display_name = "Frontend UI"
  description  = "Used by the frontend app to read Firestore and publish approved actions to Pub/Sub."
  project      = var.project_id

  depends_on = [google_project_service.apis]
}

resource "google_project_iam_member" "frontend_firestore" {
  project = var.project_id
  role    = "roles/datastore.user"
  member  = "serviceAccount:${google_service_account.frontend.email}"

  depends_on = [google_service_account.frontend]
}

resource "google_pubsub_topic_iam_member" "frontend_execute_actions_publisher" {
  project = var.project_id
  topic   = google_pubsub_topic.execute_actions.name
  role    = "roles/pubsub.publisher"
  member  = "serviceAccount:${google_service_account.frontend.email}"

  depends_on = [google_service_account.frontend, google_pubsub_topic.execute_actions]
}
